### ISSUE TITLE
Do not send non-http browsing data to the webapp

### ISSUE THREAD

**Issue by marcosmenendez** [thegooddata/extension#34]
We are still sending chrome related actions to the webapp. We should only send http or https requests. For instance, we stopped storing chrome://newtab/ transactions, but we are still sending and storing the following:
chrome-devtools://devtools/
chrome-extension://
chrome://apps/
chrome://chrome-signin/
chrome://extensions/
chrome://settings/
file:///home/

The extension should only send to the webapp browsing data that starts with http. Not even ftp or any other. Just http.

We did block somewhere the newtab transactions, if we did it in the webapp, please take out that filter from there because it will not be necessary anymore.

PLEASE delete these transactions as well from production db to avoid counting them

**Comment by JuanMenendezBuitrago** [comment]
can I take care of this one?

**Comment by atrandafir** [comment]
I think there's already something done on this so first check it.

**Comment by JuanMenendezBuitrago** [comment]
Until now, only URL beginning with 

    'chrome://newtab/',
    'chrome://settings/',
    'chrome://extensions/',
    'chrome://history/'

were ignored. Now I changed it for a regular expression in order to avoid using a list for every possible case.
