### ISSUE TITLE
A few errors in version 1.0.33

### ISSUE THREAD

**Issue by JuanMenendezBuitrago** [thegooddata/extension#37]
I've installed version 1.0.33 and I get the following errors in the popup console. I also find that the logout action in the extension is not working as it should. When I click on the logout button nothing happens right away. I log out eventually but only after clicking on the extension button to close the popup (and sometimes not even then).

![extension_error](https://cloud.githubusercontent.com/assets/5305439/7442469/0633fca2-f113-11e4-8a1f-14eaa59066bc.PNG)

**Comment by marcosmenendez** [comment]
Has this been solved @atrandafir ?

**Comment by JuanMenendezBuitrago** [comment]
I am looking into the extension's source code and realized that when we
load some pages the getLoggedUser request is sent twice. I believe this
happens because  chrome.tabs.onUpdated() event is triggered once for every
tab's property that gets updated.

Usually the only property that gets updated is the status, but sometimes
the favIconUrl is also updated which triggers the event sending a redundant
request to the server. I think this has something to do with caching
because once I have visited a page it doesn't happen again.

probably changing the condition  in background.js from

if ( tab.status=="complete" ){

to

if ( changeInfo.status=="complete" ){

fixs it.

I'll do it myself. I am just saying it here in case anyone has any
objection about this.

2015-05-05 1:13 GMT+02:00 Marcos Menendez <notifications@github.com>:

**Comment by marcosmenendez** [comment]
Is this related to this issue? https://github.com/thegooddata/webapp/issues/151

**Comment by JuanMenendezBuitrago** [comment]
It could be, because the event listener that is called twice hosts also the call for the function lookforQuery().

I can't be 100% sure but I'll look into it unless @atrandafir already has.

**Comment by JuanMenendezBuitrago** [comment]
I changed the "if" condition so now the code is executed only when the status has changed to "complete" which is the one that matters. A set of changes in the tab produced a set of calls that produced redundant requests for both login and query requests.
