### ISSUE TITLE
Waiting for TheGoodData message

### ISSUE THREAD

**Issue by marcosmenendez** [thegooddata/extension#45]
If I visit this site https://gallery.mailchimp.com/93dc40ea1346b5fbb7730bb03/files/Impulse_Subvencionado_07.pdf it doesn't download the pdf. Keeps on showing a message at the bottom saying that it is waiting for our extension to respond.

The page downloads perfectly on firefox for instance

**Comment by JuanMenendezBuitrago** [comment]
I can't reproduce this problem that you mention. Does it still happen when you try to load that page?

**Comment by marcosmenendez** [comment]
Not anymore
