### ISSUE TITLE
Enable inline installs

### ISSUE THREAD

**Issue by marcosmenendez** [thegooddata/extension#47]
In order to do so, we need to mark it in the Google web store developer dashboard. Once that the extension has been approved, we will need to change the download links in the home and the "get thegooddata" button in the header following these instructions:

https://developer.chrome.com/webstore/inline_installation

**Comment by atrandafir** [comment]
Okay enabled it in Google web store developer dashboard.

**Comment by atrandafir** [comment]
Ready in production.
